name: macOS VNC via tmate
on: workflow_dispatch
jobs:
  mac-vnc:
    runs-on: macos-latest
    steps:
      - name: Start VNC Server
        env:
          USER_PASS: secretpassword
        run: |
          echo "Setting up VNC Server..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw $USER_PASS -restart -agent -privs -all
      
      - name: Start tmate Tunnel
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
